# 02-multi-connection-static — ingress broker. No auth, no JetStream.
# Run: `nats-server -c server-ingress.conf`
port: 4223
host: 127.0.0.1
log_file: "./nats-ingress.log"
debug: false
trace: false
logtime: true
