# 02-multi-connection-static — internal broker. No auth, no JetStream.
# Run: `nats-server -c server-internal.conf`
port: 4222
host: 127.0.0.1
log_file: "./nats-internal.log"
debug: false
trace: false
logtime: true
