# System Account — natsbyexample.com/examples/auth/sys-account
# Run: nats-server -c server-sys-account.conf
port: 4222
host: 127.0.0.1
accounts {
  SYS: {
    users: [{user: "sys", password: "sys-password"}]
  }
  APP: {
    users: [{user: "app", password: "app-password"}]
  }
}
system_account: SYS
log_file: "./nats-server.log"
