# User/Password auth
# Run: nats-server -c server-userpass.conf
port: 4222
host: 127.0.0.1
authorization {
  users: [
    {user: "app", password: "app-password"},
    {user: "admin", password: "admin-password", permissions: {publish: ">", subscribe: ">"}}
  ]
}
log_file: "./nats-server.log"
