# TLS + Mutual TLS auth
# Run: bash tls/gen-certs.sh && nats-server -c server-tls.conf
port: 4222
host: 127.0.0.1
tls {
  cert_file: "./tls/server-cert.pem"
  key_file:  "./tls/server-key.pem"
  ca_file:   "./tls/ca-cert.pem"
  verify:    true       # require client cert (mTLS)
  timeout:   3
}
log_file: "./nats-server.log"
