# 01-single-connection — basic NATS broker, no auth, no JetStream.
# Run: `nats-server -c server.conf`
port: 4222
host: 127.0.0.1
log_file: "./nats-server.log"
debug: false
trace: false
logtime: true
