# 15-jetstream-filter-subject — JetStream broker. Stream EVENTS for filterSubject demos.
port: 4222
host: 127.0.0.1
log_file: "./nats-server.log"
logtime: true
jetstream {
  store_dir: "./js-store"
}
