port: 4222
host: 127.0.0.1
jetstream { store_dir: "/tmp/nats-jetstream" }
accounts: {
  SYS: {users: [{user: sys, password: sys}]}
  APP: {
    jetstream: true
    users: [{user: app, password: app}]
    mappings: {
      "events.*": "events.{{wildcard(1)}}.{{partition(5,1)}}"
    }
  }
}
system_account: SYS
log_file: "./nats-server.log"
